### ISSUE TITLE
calendar-widget: Ganztägige Serientermine werde nicht richtig angezeigt

### ISSUE THREAD

**Issue by Joerg82** [Scrounger/ioBroker.vis-materialdesign#144]
Ganztägig eingestellte Serientermine (Geburtstage) werden im Calendar-widget über 2 Tage dargestellt.
 
Ganztägige, einmalige Termine werden richtig angezeigt.

![grafik](https://user-images.githubusercontent.com/77452006/104613777-d93a9180-5687-11eb-9004-f02f751cdabe.png)

**Comment by Scrounger** [comment]
folgendes wird benötigt:
* verwendeter json string
* export deines widgets
* consolen log zur runtime (F12)

**Comment by Joerg82** [comment]
`javascript.0 (2992) script.js.common.Kalender.Skript_2: ical2MaterialDesignCalendarWidget: message: Cannot read property 'split' of undefined, stack: TypeError: Cannot read property 'split' of undefined at ical2CalendarWidget (script.js.common.Kalender.Skript_2:60:52) at script.js.common.Kalender.Skript_2:208:1 at script.js.common.Kalender.Skript_2:209:3 at Script.runInContext (vm.js:131:20) at Script.runInNewContext (vm.js:137:17) at execute (C:\iobroker\SmartHome\node_modules\iobroker.javascript\main.js:1483:27) at prepareScript (C:\iobroker\SmartHome\node_modules\iobroker.javascript\main.js:1691:38) at C:\iobroker\SmartHome\node_modules\iobroker.javascript\main.js:1791:17 at Immediate._onImmediate (C:\iobroker\SmartHome\node_modules\iobroker.javascript\main.js:1281:17) at processImmediate (internal/timers.js:458:21)`
