### ISSUE TITLE
Funktioniert mit iOS über Cloud nicht

### ISSUE THREAD

**Issue by Kusi-Schweiz** [Scrounger/ioBroker.vis-materialdesign#181]
**Describe the bug**  
Die Widgets von materialdesign werden auf iOS nicht angezeigt, wenn ioBroker über die Cloud benutzt wird.
Bei der Benutzung OHNE Cloud im heimischen Netzwerk werden die Widgets angezeigt.

iOS über Cloud:
![iOS über Cloud](https://user-images.githubusercontent.com/71840093/123258962-446c7780-d4f4-11eb-81fe-e58c02aba13f.jpeg)

iOS ohne Cloud im Heimnetzwerk:
![iOS im Netzwerk ohne Cloud](https://user-images.githubusercontent.com/71840093/123259030-53532a00-d4f4-11eb-81ba-d0d9dfb41c07.jpeg)

iOS ohne Cloud im Heimnetzwerk (andere View):
![Storen im Netzwerk ohne Cloud](https://user-images.githubusercontent.com/71840093/123259123-6b2aae00-d4f4-11eb-8240-c4468f8c62f2.jpeg)

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Browser Consolen log File**  
add the browser consolen log file from the vis runtime. 
[How to get the consolen log file](https://support.shortpoint.com/support/solutions/articles/1000222881-save-browser-s-console-file)

**Widget, View or Project Export**
Export the widget, view or project and paste it here

```
Widget Export
```

**JSON Data**
If the Widget is using json data, export the json data and paste it here

```
JSON Data
```

**Screenshots**
provide some screenshots or animated images of the issue. For example you can create this with [ScreenToGif](https://www.screentogif.com/)

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - VIS Adapter version: <vis-adapter-version>

**Additional context**

**Comment by weindler** [comment]
Nicht nur die Widgets nicht, auch das Menü wird nicht angezeigt und es kommen unendlich viel fehler im log. Er kann das nicht rendern, so lese ich das heraus. Näheres findet man in dem Post auf Github.
https://github.com/ioBroker/ioBroker.cloud/issues/214

Ich hoffe man hat hier eine Lösung parat, wäre Schade wenn das nciht gehen würde.

Geht man direkt per VPN oder im heimischen Wlan auf die Vis, dann funktioniert es, in der Cloud nicht.

**Comment by Ball-Pic** [comment]
Hallo
Kann ich leider bestätigen - einen Workaround oder Alternativlösung habe ich noch nicht gefunden (obwohl ich schon alle auf die letzten Versionen upgedatet habe.
Habt Ihr eine andere Lösung mit ähnlichen Ergebnis parat?

**Comment by weindler** [comment]
ich wollte mal den Post wieder nach vorne bringen, da es ja die verbilligten wiehnachtslizensen gibt, aber leider kann ich ja damit nichts anfangen da über die cloud das mit den meisten widgets vom materialdesign ja nciht funktioniert. Könntet ihr beiden Entwickler nicht doch einmal drüberschauen wo das Problem liegt, ich würde euch auch mit den Fehlercodes unterstützen, habe ja nicht ich alleine das Problem. Danke im Voraus

**Comment by Kusi-Schweiz** [comment]
Dieses Problem betrifft aber nur iOS, mit Android funktionieren die Widgets über die Cloud.

**Comment by weindler** [comment]
> Dieses Problem betrifft aber nur iOS, mit Android funktionieren die Widgets über die Cloud.

Nein, es funktioniert bei mir mit gar nichts, weder auf dem PC wenn ich über die Cloud reingehe noch Android.
Siehe hier, dies war ein Zugang über firefox auf dem PC

`<html><body>


2021-12-08 18:26:41.712  - error: cloud.0 (1049) Addon vis can't render tplVis-materialdesign-TopAppBar-Navigation w00033 on "Smart_Home":
--
2021-12-08 18:26:41.715  - error: cloud.0 (1049) Addon vis 0 - TypeError: vis.binds.materialdesign.topappbarnav is not a functionthis.fn/


</body>
</html>`

**Comment by Kusi-Schweiz** [comment]
> es funktioniert bei mir mit gar nichts

komisch, aber mir fällt gerade auf dass bei mir auch nur ein Teil auf Android funktioniert.
**Screenshot am PC**
![image](https://user-images.githubusercontent.com/71840093/145705017-84de0733-7f54-4978-b27f-9e7319f144fc.png)

**Screenshot bei Android über Cloud**
![image](https://user-images.githubusercontent.com/71840093/145705040-52b568e7-7417-46d4-8e5d-11c37d4a7b4c.png)

**Und hier das Log:**
<html>
<body>


cloud.0 | 2021-12-12 09:01:58.530 | error | Addon DashUI 31 - at WebSocket.ws.onmessage (file:///android_asset/www/lib/js/socket.io.js:8:6598)
-- | -- | -- | --
cloud.0 | 2021-12-12 09:01:58.530 | error | Addon DashUI 30 - at r.onData (file:///android_asset/www/lib/js/socket.io.js:7:15170)
cloud.0 | 2021-12-12 09:01:58.524 | error | Addon DashUI 29 - at r.onPacket (file:///android_asset/www/lib/js/socket.io.js:7:15221)
cloud.0 | 2021-12-12 09:01:58.524 | error | Addon DashUI 28 - at r.emit (file:///android_asset/www/lib/js/socket.io.js:6:19839)
cloud.0 | 2021-12-12 09:01:58.524 | error | Addon DashUI 27 - at r.<anonymous> (file:///android_asset/www/lib/js/socket.io.js:7:564)
cloud.0 | 2021-12-12 09:01:58.524 | error | Addon DashUI 26 - at r.onPacket (file:///android_asset/www/lib/js/socket.io.js:7:2952)
cloud.0 | 2021-12-12 09:01:58.524 | error | Addon DashUI 25 - at r.emit (file:///android_asset/www/lib/js/socket.io.js:6:19839)
cloud.0 | 2021-12-12 09:01:58.524 | error | Addon DashUI 24 - at r.<anonymous> (file:///android_asset/www/lib/js/socket.io.js:8:12358)
cloud.0 | 2021-12-12 09:01:58.524 | error | Addon DashUI 23 - at r.ondata (file:///android_asset/www/lib/js/socket.io.js:6:25536)
cloud.0 | 2021-12-12 09:01:58.523 | error | Addon DashUI 22 - at a.add (file:///android_asset/www/lib/js/socket.io.js:6:12498)
cloud.0 | 2021-12-12 09:01:58.523 | error | Addon DashUI 21 - at a.r.emit (file:///android_asset/www/lib/js/socket.io.js:6:19839)
cloud.0 | 2021-12-12 09:01:58.523 | error | Addon DashUI 20 - at a.<anonymous> (file:///android_asset/www/lib/js/socket.io.js:8:12358)
cloud.0 | 2021-12-12 09:01:58.522 | error | Addon DashUI 19 - at r.ondecoded (file:///android_asset/www/lib/js/socket.io.js:6:25583)
cloud.0 | 2021-12-12 09:01:58.522 | error | Addon DashUI 18 - at r.emit (file:///android_asset/www/lib/js/socket.io.js:6:19839)
cloud.0 | 2021-12-12 09:01:58.522 | error | Addon DashUI 17 - at r.<anonymous> (file:///android_asset/www/lib/js/socket.io.js:8:12358)
cloud.0 | 2021-12-12 09:01:58.522 | error | Addon DashUI 16 - at r.onpacket (file:///android_asset/www/lib/js/socket.io.js:8:10272)
cloud.0 | 2021-12-12 09:01:58.522 | error | Addon DashUI 15 - at r.onack (file:///android_asset/www/lib/js/socket.io.js:8:10904)
cloud.0 | 2021-12-12 09:01:58.521 | error | Addon DashUI 14 - at r.<anonymous> (file:///android_asset/www/js/conn.js:792:21)
cloud.0 | 2021-12-12 09:01:58.521 | error | Addon DashUI 13 - at file:///android_asset/www/js/vis.js:2865:31
cloud.0 | 2021-12-12 09:01:58.521 | error | Addon DashUI 12 - at file:///android_asset/www/js/vis.js:916:120
cloud.0 | 2021-12-12 09:01:58.513 | error | Addon DashUI 11 - at Object.renderWidget (file:///android_asset/www/js/vis.js:1629:33)
cloud.0 | 2021-12-12 09:01:58.511 | error | Addon DashUI 10 - at Object.e.view.e.template (file:///android_asset/www/lib/js/can.custom.min.js:58:1267)
cloud.0 | 2021-12-12 09:01:58.511 | error | Addon DashUI 9 - at Function.renderAs (file:///android_asset/www/lib/js/can.custom.min.js:58:3466)
cloud.0 | 2021-12-12 09:01:58.500 | error | Addon DashUI 8 - at file:///android_asset/www/lib/js/can.custom.min.js:46:3358
cloud.0 | 2021-12-12 09:01:58.500 | error | Addon DashUI 7 - at o (file:///android_asset/www/lib/js/can.custom.min.js:58:899)
cloud.0 | 2021-12-12 09:01:58.499 | error | Addon DashUI 6 - at Object.ajax (file:///android_asset/www/lib/js/jquery-1.11.2.min.js:4:21557)
cloud.0 | 2021-12-12 09:01:58.499 | error | Addon DashUI 5 - at x (file:///android_asset/www/lib/js/jquery-1.11.2.min.js:4:22086)
cloud.0 | 2021-12-12 09:01:58.498 | error | Addon DashUI 4 - at Object.fireWith [as rejectWith] (file:///android_asset/www/lib/js/jquery-1.11.2.min.js:2:28108)
cloud.0 | 2021-12-12 09:01:58.498 | error | Addon DashUI 3 - at j (file:///android_asset/www/lib/js/jquery-1.11.2.min.js:2:27295)
cloud.0 | 2021-12-12 09:01:58.498 | error | Addon DashUI 2 - at Object.error (file:///android_asset/www/lib/js/can.custom.min.js:58:953)
cloud.0 | 2021-12-12 09:01:58.497 | error | Addon DashUI 1 - at u (file:///android_asset/www/lib/js/can.custom.min.js:58:256)
cloud.0 | 2021-12-12 09:01:58.497 | error | Addon DashUI 0 - Error: can.view: No template or empty template:tplVis-materialdesign-value.ejsError: can.view: No template or empty template:tplVis-materialdesign-value.ejs
cloud.0 | 2021-12-12 09:01:58.496 | error | Addon DashUI can't render tplVis-materialdesign-value w00099 on "leer":


</body>
</html>`

**Comment by Kusi-Schweiz** [comment]
So sieht es auf Android **ohne Cloud** aus:
![Screenshot_20211212-090443](https://user-images.githubusercontent.com/71840093/145705142-2570d849-2f6b-41ac-959e-818b8dc2f803.jpg)

**Comment by weindler** [comment]
> > es funktioniert bei mir mit gar nichts
> 
> komisch, aber mir fällt gerade auf dass bei mir auch nur ein Teil auf Android funktioniert. **Screenshot am PC** ![image](https://user-images.githubusercontent.com/71840093/145705017-84de0733-7f54-4978-b27f-9e7319f144fc.png)
> 
> **Screenshot bei Android über Cloud** ![image](https://user-images.githubusercontent.com/71840093/145705040-52b568e7-7417-46d4-8e5d-11c37d4a7b4c.png)
> 
> **Und hier das Log:**
> cloud.0 	2021-12-12 09:01:58.530 	error 	Addon DashUI 31 - at WebSocket.ws.onmessage (file:///android_asset/www/lib/js/socket.io.js:8:6598)
> cloud.0 	2021-12-12 09:01:58.530 	error 	Addon DashUI 30 - at r.onData (file:///android_asset/www/lib/js/socket.io.js:7:15170)
> cloud.0 	2021-12-12 09:01:58.524 	error 	Addon DashUI 29 - at r.onPacket (file:///android_asset/www/lib/js/socket.io.js:7:15221)
> cloud.0 	2021-12-12 09:01:58.524 	error 	Addon DashUI 28 - at r.emit (file:///android_asset/www/lib/js/socket.io.js:6:19839)
> cloud.0 	2021-12-12 09:01:58.524 	error 	Addon DashUI 27 - at r. (file:///android_asset/www/lib/js/socket.io.js:7:564)
> cloud.0 	2021-12-12 09:01:58.524 	error 	Addon DashUI 26 - at r.onPacket (file:///android_asset/www/lib/js/socket.io.js:7:2952)
> cloud.0 	2021-12-12 09:01:58.524 	error 	Addon DashUI 25 - at r.emit (file:///android_asset/www/lib/js/socket.io.js:6:19839)
> cloud.0 	2021-12-12 09:01:58.524 	error 	Addon DashUI 24 - at r. (file:///android_asset/www/lib/js/socket.io.js:8:12358)
> cloud.0 	2021-12-12 09:01:58.524 	error 	Addon DashUI 23 - at r.ondata (file:///android_asset/www/lib/js/socket.io.js:6:25536)
> cloud.0 	2021-12-12 09:01:58.523 	error 	Addon DashUI 22 - at a.add (file:///android_asset/www/lib/js/socket.io.js:6:12498)
> cloud.0 	2021-12-12 09:01:58.523 	error 	Addon DashUI 21 - at a.r.emit (file:///android_asset/www/lib/js/socket.io.js:6:19839)
> cloud.0 	2021-12-12 09:01:58.523 	error 	Addon DashUI 20 - at a. (file:///android_asset/www/lib/js/socket.io.js:8:12358)
> cloud.0 	2021-12-12 09:01:58.522 	error 	Addon DashUI 19 - at r.ondecoded (file:///android_asset/www/lib/js/socket.io.js:6:25583)
> cloud.0 	2021-12-12 09:01:58.522 	error 	Addon DashUI 18 - at r.emit (file:///android_asset/www/lib/js/socket.io.js:6:19839)
> cloud.0 	2021-12-12 09:01:58.522 	error 	Addon DashUI 17 - at r. (file:///android_asset/www/lib/js/socket.io.js:8:12358)
> cloud.0 	2021-12-12 09:01:58.522 	error 	Addon DashUI 16 - at r.onpacket (file:///android_asset/www/lib/js/socket.io.js:8:10272)
> cloud.0 	2021-12-12 09:01:58.522 	error 	Addon DashUI 15 - at r.onack (file:///android_asset/www/lib/js/socket.io.js:8:10904)
> cloud.0 	2021-12-12 09:01:58.521 	error 	Addon DashUI 14 - at r. (file:///android_asset/www/js/conn.js:792:21)
> cloud.0 	2021-12-12 09:01:58.521 	error 	Addon DashUI 13 - at file:///android_asset/www/js/vis.js:2865:31
> cloud.0 	2021-12-12 09:01:58.521 	error 	Addon DashUI 12 - at file:///android_asset/www/js/vis.js:916:120
> cloud.0 	2021-12-12 09:01:58.513 	error 	Addon DashUI 11 - at Object.renderWidget (file:///android_asset/www/js/vis.js:1629:33)
> cloud.0 	2021-12-12 09:01:58.511 	error 	Addon DashUI 10 - at Object.e.view.e.template (file:///android_asset/www/lib/js/can.custom.min.js:58:1267)
> cloud.0 	2021-12-12 09:01:58.511 	error 	Addon DashUI 9 - at Function.renderAs (file:///android_asset/www/lib/js/can.custom.min.js:58:3466)
> cloud.0 	2021-12-12 09:01:58.500 	error 	Addon DashUI 8 - at file:///android_asset/www/lib/js/can.custom.min.js:46:3358
> cloud.0 	2021-12-12 09:01:58.500 	error 	Addon DashUI 7 - at o (file:///android_asset/www/lib/js/can.custom.min.js:58:899)
> cloud.0 	2021-12-12 09:01:58.499 	error 	Addon DashUI 6 - at Object.ajax (file:///android_asset/www/lib/js/jquery-1.11.2.min.js:4:21557)
> cloud.0 	2021-12-12 09:01:58.499 	error 	Addon DashUI 5 - at x (file:///android_asset/www/lib/js/jquery-1.11.2.min.js:4:22086)
> cloud.0 	2021-12-12 09:01:58.498 	error 	Addon DashUI 4 - at Object.fireWith [as rejectWith] (file:///android_asset/www/lib/js/jquery-1.11.2.min.js:2:28108)
> cloud.0 	2021-12-12 09:01:58.498 	error 	Addon DashUI 3 - at j (file:///android_asset/www/lib/js/jquery-1.11.2.min.js:2:27295)
> cloud.0 	2021-12-12 09:01:58.498 	error 	Addon DashUI 2 - at Object.error (file:///android_asset/www/lib/js/can.custom.min.js:58:953)
> cloud.0 	2021-12-12 09:01:58.497 	error 	Addon DashUI 1 - at u (file:///android_asset/www/lib/js/can.custom.min.js:58:256)
> cloud.0 	2021-12-12 09:01:58.497 	error 	Addon DashUI 0 - Error: can.view: No template or empty template:tplVis-materialdesign-value.ejsError: can.view: No template or empty template:tplVis-materialdesign-value.ejs
> cloud.0 	2021-12-12 09:01:58.496 	error 	Addon DashUI can't render tplVis-materialdesign-value w00099 on "leer":
> `

sag ich doch, mir kommt das vor als sei das material design widget nicht kompatibel mit der cloud, mir geht es seit anfang an so, es wird aber leider nicht zusammen dran gearbeitet, ich habe nun schon fast in allen kanälen das problem gepostet. ich würde halt gerne vom vpn zugang weggehen, so könnte man das sauber über die cloud laufen lassen, dazu habe ich das problem wenn ich im 3g oder lte netz bin, dann kann ich keinen zugang über vpn zur fritz box also auch zum smart home herstellen geht nur über wlan, mit der cloud hätte ich überall aus zugriff. habe ja mittlerweile meine ganzen termine über iobroker laufen und da wäre es schon cool wenn man hier nun in den nächsten wochen mal eine lösung finden würde. Denn ansonsten muß ich mich wohl meine Vis komplett neu aufbauen und mich dann vom material design widget trennen.

Ich würde mich ja bereit erklären hier meinetwegen über team viewer mit den entwicklern zusammenarbeiten damit hier endlich eine lösung gefunden wird.

**Comment by Doreinie** [comment]
Hallo, ich habe das gleiche Problem und auch gepostet und erhalte keine Antwort. Egal ob Computer, Laptop, Andriod oder iOS. wenn über Cloud auf VIS zugegriffen wird dann zeigen sich die Materialdesign Widgets nicht und es kommt zu einer Reihe von Fehlern im Log.

**Comment by Doreinie** [comment]
Habe heute erfahren das es daran liegt: materialdesign hat keinen stable release. daher wird es nicht ins VIS Cloud aufgenommen. :-(

**Comment by weindler** [comment]
Ja, so weit weiß ich das auch, ich hoffe daß das dieses Jahr über die Bühne geht, wäre super.

**Comment by Dette70** [comment]
@Scrounger wird den an dem Adapter noch gearbeitet oder hat sich das erledigt?

Wenigstens eine finale stable Version würde ja schon helfen.
Besten Dank.
