### ISSUE TITLE
Widgets werden in Opera und Firefox dargestellt, in Chrome nicht

### ISSUE THREAD

**Issue by fu-zhou** [Scrounger/ioBroker.vis-materialdesign#94]
Hi,

ich habe die Checkbox und Line History Chart im Einsatz. Beide werden in Opera und Firefox in der vis Runtime dargestellt, in Chrome aber nicht (Windows und Linux, probiert auf 2 verschiedenen PCs). Android Chrome zeigt die Widgets.
Im vis Editor sind die Widgets in Chrome zu sehen. Chrome ist jeweils die aktuelle Version, Linux:
`Version 81.0.4044.138 (Offizieller Build) Built on Ubuntu , running on LinuxMint 19.3 (64-Bit)`

**Comment by Scrounger** [comment]
Kann ich nicht reproduzieren.

Welche MDW Version?
Was steht in der console log des browsers?

**Comment by fu-zhou** [comment]
Chrome Console:
```
jquery-1.11.2.min.js:4 GET http://192.168.0.50:8082/vis/tplVis-materialdesign-Chart-Line-History.ejs 404 (Not Found)
send @ jquery-1.11.2.min.js:4
ajax @ jquery-1.11.2.min.js:4
o @ can.custom.min.js:58
(anonymous) @ can.custom.min.js:46
renderAs @ can.custom.min.js:58
e.view.e.template @ can.custom.min.js:58
renderWidget @ vis.js:1610
(anonymous) @ vis.js:887
(anonymous) @ vis.js:2742
(anonymous) @ conn.js:730
r.onack @ socket.io.js:8
r.onpacket @ socket.io.js:8
(anonymous) @ socket.io.js:8
r.emit @ socket.io.js:6
r.ondecoded @ socket.io.js:6
(anonymous) @ socket.io.js:8
r.emit @ socket.io.js:6
a.add @ socket.io.js:6
r.ondata @ socket.io.js:6
(anonymous) @ socket.io.js:8
r.emit @ socket.io.js:6
r.onPacket @ socket.io.js:7
(anonymous) @ socket.io.js:7
r.emit @ socket.io.js:6
r.onPacket @ socket.io.js:7
r.onData @ socket.io.js:7
ws.onmessage @ socket.io.js:8
conn.js:1142 Error: can't render tplVis-materialdesign-Chart-Line-History w01504 on "HV_Wetterstation": 
conn.js:1142 Error: 0 - Error: can.view: No template or empty template:tplVis-materialdesign-Chart-Line-History.ejsError: can.view: No template or empty template:tplVis-materialdesign-Chart-Line-History.ejs
conn.js:1142 Error: 1 -     at u (http://192.168.0.50:8082/vis/lib/js/can.custom.min.js:58:256)
conn.js:1142 Error: 2 -     at Object.error (http://192.168.0.50:8082/vis/lib/js/can.custom.min.js:58:953)
conn.js:1142 Error: 3 -     at j (http://192.168.0.50:8082/lib/js/jquery-1.11.2.min.js:2:27295)
conn.js:1142 Error: 4 -     at Object.fireWith [as rejectWith] (http://192.168.0.50:8082/lib/js/jquery-1.11.2.min.js:2:28108)
conn.js:1142 Error: 5 -     at x (http://192.168.0.50:8082/lib/js/jquery-1.11.2.min.js:4:22086)
conn.js:1142 Error: 6 -     at b (http://192.168.0.50:8082/lib/js/jquery-1.11.2.min.js:4:25980)
conn.js:1142 Error: 7 -     at Object.send (http://192.168.0.50:8082/lib/js/jquery-1.11.2.min.js:4:26084)
conn.js:1142 Error: 8 -     at Object.ajax (http://192.168.0.50:8082/lib/js/jquery-1.11.2.min.js:4:21520)
conn.js:1142 Error: 9 -     at o (http://192.168.0.50:8082/vis/lib/js/can.custom.min.js:58:899)
conn.js:1142 Error: 10 -     at http://192.168.0.50:8082/vis/lib/js/can.custom.min.js:46:3358
```
Bei Opera bleibt die Konsole leer.

**Comment by fu-zhou** [comment]
Cache löschen war die Lösung!
